### ISSUE TITLE
error: exec: "./script/start.sh": stat ./script/start.sh: no such file or directory

### ISSUE THREAD

**Issue by grisuthedragon** [csf-ngs/hinkskalle#32]
After fixing the "Hinkskalle.uitl" python error I now get:
```
api_1           | error: exec: "./script/start.sh": stat ./script/start.sh: no such file or directory
```

I use the plain docker-compose.yml from `share/deploy` and commented out all LDAP related stuff from the environment files. I set the system up by:
```
docker-compose up -d hinkdb
docker-compose run --rm api flask db upgrade
docker-compose run --rm api flask localdb add-user   -u admin   -p admin   -e admin@testha.se   -f Admin -l Hase   --admin
docker-compose up 
```

**Comment by h3kker** [comment]
Oops, the start script expected to be started in a particular directory. I made the whole thing more robust. You will need to pull the fresh docker image (`docker-compose pull api`).

**Comment by h3kker** [comment]
fixed in c33322b

**Comment by grisuthedragon** [comment]
This works now. But the login is not possible. Neither the created admin user nor the standard user can login. Both return a `401`.

**Comment by h3kker** [comment]
Ah, you have to change `HINKSKALLE_BACKEND_URL`, if you use the share/deploy stuff it's in `conf/hinkskalle.env`. 

for disabling LDAP `HINKSKALLE_LDAP_BIND_PASSWORD` should also be commented out. 

I've pushed e25a5dc with localhost as backend url and ldap disabled in the example deployment, I think this might be a more common use case for trying it out.

documentation also updated: https://testha.se/projects/hinkskalle/deployment/#backend-url

**Comment by grisuthedragon** [comment]
Now everything works as expected. Thanks :-)
