### ISSUE TITLE
default quota fpr new users

### ISSUE THREAD

**Issue by grisuthedragon** [csf-ngs/hinkskalle#43]
After running hinkskalle now for two months, we found a nice to have enhancement. It would be great if we can set a default quota for users and groups on their first login or when the group is created.

**Comment by h3kker** [comment]
there is a config option: https://github.com/csf-ngs/hinkskalle/blob/master/docs/configuration.md?plain=1#L41

see also here: https://csf-ngs.github.io/hinkskalle/configuration.html, but I can't link directly there, it seems.

But it only applies as a db default for new entities. It should be

- a field on the user/group object
- preset to the default config value
- applied to new entities for this user/group

**Comment by h3kker** [comment]
@grisuthedragon I did a bit of a rewrite of the whole quota handling. It was based on entities for $reasons, but that does not work so well when groups come into play. So now it's based on users (and images uploaded by users, no matter where) and groups (still tied to the entity). Quotas can be changed in the user and group views (admins only).

Details are here: https://github.com/csf-ngs/hinkskalle/blob/43-default-quota-for-new-users/docs/quotas.md

Maybe you would like to give it a go: 

```
docker pull ghcr.io/csf-ngs/hinkskalle:43-default-quota-for-new-users
```

and let me know what you think?

**Comment by grisuthedragon** [comment]
I will take a look on this asap. But reading the description it sounds good.
